package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class PolishedBlackstoneBrickStairs {
  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_0 = new BlockState((short) 16268, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_1 = new BlockState((short) 16269, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_2 = new BlockState((short) 16270, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_3 = new BlockState((short) 16271, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_4 = new BlockState((short) 16272, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_5 = new BlockState((short) 16273, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_6 = new BlockState((short) 16274, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_7 = new BlockState((short) 16275, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_8 = new BlockState((short) 16276, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_9 = new BlockState((short) 16277, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_10 = new BlockState((short) 16278, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_11 = new BlockState((short) 16279, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_12 = new BlockState((short) 16280, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_13 = new BlockState((short) 16281, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_14 = new BlockState((short) 16282, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_15 = new BlockState((short) 16283, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_16 = new BlockState((short) 16284, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_17 = new BlockState((short) 16285, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_18 = new BlockState((short) 16286, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_19 = new BlockState((short) 16287, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_20 = new BlockState((short) 16288, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_21 = new BlockState((short) 16289, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_22 = new BlockState((short) 16290, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_23 = new BlockState((short) 16291, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_24 = new BlockState((short) 16292, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_25 = new BlockState((short) 16293, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_26 = new BlockState((short) 16294, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_27 = new BlockState((short) 16295, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_28 = new BlockState((short) 16296, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_29 = new BlockState((short) 16297, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_30 = new BlockState((short) 16298, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_31 = new BlockState((short) 16299, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_32 = new BlockState((short) 16300, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_33 = new BlockState((short) 16301, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_34 = new BlockState((short) 16302, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_35 = new BlockState((short) 16303, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_36 = new BlockState((short) 16304, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_37 = new BlockState((short) 16305, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_38 = new BlockState((short) 16306, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_39 = new BlockState((short) 16307, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_40 = new BlockState((short) 16308, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_41 = new BlockState((short) 16309, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_42 = new BlockState((short) 16310, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_43 = new BlockState((short) 16311, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_44 = new BlockState((short) 16312, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_45 = new BlockState((short) 16313, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_46 = new BlockState((short) 16314, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_47 = new BlockState((short) 16315, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_48 = new BlockState((short) 16316, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_49 = new BlockState((short) 16317, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_50 = new BlockState((short) 16318, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_51 = new BlockState((short) 16319, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_52 = new BlockState((short) 16320, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_53 = new BlockState((short) 16321, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_54 = new BlockState((short) 16322, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_55 = new BlockState((short) 16323, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_56 = new BlockState((short) 16324, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_57 = new BlockState((short) 16325, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_58 = new BlockState((short) 16326, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_59 = new BlockState((short) 16327, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_60 = new BlockState((short) 16328, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_61 = new BlockState((short) 16329, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_62 = new BlockState((short) 16330, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_63 = new BlockState((short) 16331, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_64 = new BlockState((short) 16332, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_65 = new BlockState((short) 16333, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_66 = new BlockState((short) 16334, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_67 = new BlockState((short) 16335, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_68 = new BlockState((short) 16336, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_69 = new BlockState((short) 16337, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_70 = new BlockState((short) 16338, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_71 = new BlockState((short) 16339, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_72 = new BlockState((short) 16340, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_73 = new BlockState((short) 16341, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_74 = new BlockState((short) 16342, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_75 = new BlockState((short) 16343, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_76 = new BlockState((short) 16344, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_77 = new BlockState((short) 16345, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_78 = new BlockState((short) 16346, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_BRICK_STAIRS_79 = new BlockState((short) 16347, Block.POLISHED_BLACKSTONE_BRICK_STAIRS);

  public static void initStates() {
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_0);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_1);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_2);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_3);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_4);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_5);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_6);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_7);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_8);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_9);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_10);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_11);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_12);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_13);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_14);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_15);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_16);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_17);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_18);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_19);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_20);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_21);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_22);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_23);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_24);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_25);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_26);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_27);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_28);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_29);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_30);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_31);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_32);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_33);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_34);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_35);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_36);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_37);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_38);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_39);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_40);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_41);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_42);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_43);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_44);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_45);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_46);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_47);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_48);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_49);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_50);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_51);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_52);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_53);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_54);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_55);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_56);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_57);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_58);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_59);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_60);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_61);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_62);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_63);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_64);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_65);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_66);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_67);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_68);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_69);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_70);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_71);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_72);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_73);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_74);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_75);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_76);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_77);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_78);
    Block.POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockState(POLISHED_BLACKSTONE_BRICK_STAIRS_79);
  }
}
