package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class PolishedBlackstoneStairs {
  public static final BlockState POLISHED_BLACKSTONE_STAIRS_0 = new BlockState((short) 16673, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_1 = new BlockState((short) 16674, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_2 = new BlockState((short) 16675, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_3 = new BlockState((short) 16676, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_4 = new BlockState((short) 16677, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_5 = new BlockState((short) 16678, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_6 = new BlockState((short) 16679, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_7 = new BlockState((short) 16680, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_8 = new BlockState((short) 16681, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_9 = new BlockState((short) 16682, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_10 = new BlockState((short) 16683, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_11 = new BlockState((short) 16684, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_12 = new BlockState((short) 16685, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_13 = new BlockState((short) 16686, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_14 = new BlockState((short) 16687, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_15 = new BlockState((short) 16688, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_16 = new BlockState((short) 16689, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_17 = new BlockState((short) 16690, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_18 = new BlockState((short) 16691, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_19 = new BlockState((short) 16692, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_20 = new BlockState((short) 16693, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_21 = new BlockState((short) 16694, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_22 = new BlockState((short) 16695, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_23 = new BlockState((short) 16696, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_24 = new BlockState((short) 16697, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_25 = new BlockState((short) 16698, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_26 = new BlockState((short) 16699, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_27 = new BlockState((short) 16700, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_28 = new BlockState((short) 16701, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_29 = new BlockState((short) 16702, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_30 = new BlockState((short) 16703, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_31 = new BlockState((short) 16704, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_32 = new BlockState((short) 16705, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_33 = new BlockState((short) 16706, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_34 = new BlockState((short) 16707, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_35 = new BlockState((short) 16708, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_36 = new BlockState((short) 16709, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_37 = new BlockState((short) 16710, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_38 = new BlockState((short) 16711, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_39 = new BlockState((short) 16712, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_40 = new BlockState((short) 16713, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_41 = new BlockState((short) 16714, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_42 = new BlockState((short) 16715, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_43 = new BlockState((short) 16716, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_44 = new BlockState((short) 16717, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_45 = new BlockState((short) 16718, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_46 = new BlockState((short) 16719, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_47 = new BlockState((short) 16720, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_48 = new BlockState((short) 16721, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_49 = new BlockState((short) 16722, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_50 = new BlockState((short) 16723, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_51 = new BlockState((short) 16724, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_52 = new BlockState((short) 16725, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_53 = new BlockState((short) 16726, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_54 = new BlockState((short) 16727, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_55 = new BlockState((short) 16728, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_56 = new BlockState((short) 16729, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_57 = new BlockState((short) 16730, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_58 = new BlockState((short) 16731, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_59 = new BlockState((short) 16732, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_60 = new BlockState((short) 16733, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_61 = new BlockState((short) 16734, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_62 = new BlockState((short) 16735, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_63 = new BlockState((short) 16736, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_64 = new BlockState((short) 16737, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_65 = new BlockState((short) 16738, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_66 = new BlockState((short) 16739, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_67 = new BlockState((short) 16740, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_68 = new BlockState((short) 16741, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_69 = new BlockState((short) 16742, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_70 = new BlockState((short) 16743, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_71 = new BlockState((short) 16744, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_72 = new BlockState((short) 16745, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_73 = new BlockState((short) 16746, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_74 = new BlockState((short) 16747, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_75 = new BlockState((short) 16748, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_76 = new BlockState((short) 16749, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_77 = new BlockState((short) 16750, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_78 = new BlockState((short) 16751, Block.POLISHED_BLACKSTONE_STAIRS);

  public static final BlockState POLISHED_BLACKSTONE_STAIRS_79 = new BlockState((short) 16752, Block.POLISHED_BLACKSTONE_STAIRS);

  public static void initStates() {
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_0);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_1);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_2);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_3);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_4);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_5);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_6);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_7);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_8);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_9);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_10);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_11);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_12);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_13);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_14);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_15);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_16);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_17);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_18);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_19);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_20);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_21);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_22);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_23);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_24);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_25);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_26);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_27);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_28);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_29);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_30);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_31);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_32);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_33);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_34);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_35);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_36);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_37);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_38);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_39);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_40);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_41);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_42);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_43);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_44);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_45);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_46);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_47);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_48);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_49);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_50);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_51);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_52);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_53);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_54);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_55);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_56);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_57);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_58);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_59);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_60);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_61);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_62);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_63);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_64);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_65);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_66);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_67);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_68);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_69);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_70);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_71);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_72);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_73);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_74);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_75);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_76);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_77);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_78);
    Block.POLISHED_BLACKSTONE_STAIRS.addBlockState(POLISHED_BLACKSTONE_STAIRS_79);
  }
}
