package com.minestom.code_generator;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.stream.JsonReader;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class CodeGenerator {
    private static final Logger LOGGER = LoggerFactory.getLogger(CodeGenerator.class);
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
    private static final File INPUT_FOLDER = new File("../../DataGenerator/output/");

    public static void main(String[] args) {
        if (args.length == 0) {
            LOGGER.info("You must specify a version to generate data for.");
            return;
        }
        // version for the output.
        String version = args[0];
        File outputFolder = new File("../../AutoGenerated/" + version + "/");
        // Create output folder
        if (!outputFolder.exists() && !outputFolder.mkdirs()) {
            throw new ExceptionInInitializerError("Failed to create output folder.");
        }

        generateBlocks(new File(INPUT_FOLDER, version.replaceAll("\\.", "_") + "_blocks.json"), outputFolder);
        generateEntities(new File(INPUT_FOLDER, version.replaceAll("\\.", "_") + "_entities.json"), outputFolder);
        generateBlockEntities(new File(INPUT_FOLDER, version.replaceAll("\\.", "_") + "_block_entities.json"), outputFolder);
        generateItems(new File(INPUT_FOLDER, version.replaceAll("\\.", "_") + "_items.json"), outputFolder);
    }

    public static void generateBlocks(File inputFile, File outputFolder) {
        JsonArray blocks;

        try {
            blocks = GSON.fromJson(new JsonReader(new FileReader(inputFile)), JsonArray.class);
        } catch (FileNotFoundException e) {
            LOGGER.error("Failed to find blocks.json, stopped generating code for blocks", e);
            return;
        }
        ClassName blockClassName = ClassName.get("net.minestom.server.instance.block", "Block");
        ClassName blockStateClassName = ClassName.get("net.minestom.server.instance.block", "BlockState");

        // Block
        TypeSpec.Builder blockClass = TypeSpec.classBuilder(blockClassName).addModifiers(Modifier.PUBLIC);
        blockClass.addField(FieldSpec.builder(String.class, "id").addModifiers(Modifier.PRIVATE, Modifier.FINAL).addAnnotation(NotNull.class).build());
        blockClass.addField(FieldSpec.builder(TypeName.SHORT, "defaultBlockState").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        blockClass.addField(FieldSpec.builder(TypeName.DOUBLE, "explosionResistance").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        blockClass.addField(FieldSpec.builder(TypeName.DOUBLE, "friction").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        blockClass.addField(FieldSpec.builder(TypeName.DOUBLE, "speedFactor").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        blockClass.addField(FieldSpec.builder(TypeName.DOUBLE, "jumpFactor").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        blockClass.addField(FieldSpec.builder(String.class, "itemId").addModifiers(Modifier.PRIVATE, Modifier.FINAL).addAnnotation(Nullable.class).build());
        blockClass.addField(
                FieldSpec.builder(ParameterizedTypeName.get(ClassName.get("java.util", "List"), blockStateClassName), "blockStates")
                        .initializer("new $T<>()", ClassName.get("java.util", "ArrayList"))
                        .addModifiers(Modifier.PRIVATE, Modifier.FINAL)
                        .addAnnotation(NotNull.class)
                        .build()
        );
        blockClass.addMethod(
                MethodSpec.constructorBuilder()
                        .addParameter(ParameterSpec.builder(String.class, "id").addAnnotation(NotNull.class).build())
                        .addParameter(TypeName.SHORT, "defaultBlockState")
                        .addParameter(TypeName.DOUBLE, "explosionResistance")
                        .addParameter(TypeName.DOUBLE, "friction")
                        .addParameter(TypeName.DOUBLE, "speedFactor")
                        .addParameter(TypeName.DOUBLE, "jumpFactor")
                        .addParameter(ParameterSpec.builder(String.class, "itemId").addAnnotation(Nullable.class).build())

                        .addStatement("this.id = id")
                        .addStatement("this.defaultBlockState = defaultBlockState")
                        .addStatement("this.explosionResistance = explosionResistance")
                        .addStatement("this.friction = friction")
                        .addStatement("this.speedFactor = speedFactor")
                        .addStatement("this.jumpFactor = jumpFactor")
                        .addStatement("this.itemId = itemId")
                        .addModifiers(Modifier.PROTECTED)
                        .build()
        );
        // Block constructor
        blockClass.addMethod(
                MethodSpec.methodBuilder("addBlockState")
                        .addParameter(ParameterSpec.builder(blockStateClassName, "blockState").addAnnotation(NotNull.class).build())

                        .addStatement("this.blockStates.add(blockState)")
                        .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                        .build()
        );

        // BlockState
        TypeSpec.Builder blockStateClass = TypeSpec.classBuilder(blockStateClassName).addModifiers(Modifier.PUBLIC);
        blockStateClass.addField(FieldSpec.builder(TypeName.SHORT, "id").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        blockStateClass.addField(FieldSpec.builder(blockClassName, "block").addModifiers(Modifier.PRIVATE, Modifier.FINAL).addAnnotation(NotNull.class).build());
        // BlockState constructor
        blockStateClass.addMethod(
                MethodSpec.constructorBuilder()
                        .addParameter(TypeName.SHORT, "id")
                        .addParameter(ParameterSpec.builder(blockClassName, "block").addAnnotation(NotNull.class).build())

                        .addStatement("this.id = id")
                        .addStatement("this.block = block")
                        .addModifiers(Modifier.PUBLIC)
                        .build()
        );

        // For static initStates
        CodeBlock.Builder staticBlock = CodeBlock.builder();

        // Use data
        for (JsonElement b : blocks) {
            JsonObject block = b.getAsJsonObject();

            String blockName = block.get("name").getAsString();
            // Handle defaults:
            String itemId = block.get("itemId").getAsString();
            if (itemId.equals("minecraft:air")) {
                itemId = null;
            }

            blockClass.addField(
                    FieldSpec.builder(
                            blockClassName,
                            blockName
                    ).initializer(
                            "new $T($S, (short) $L, $L, $L, $L, $L, $S)",
                            blockClassName,
                            block.get("id").getAsString(),
                            block.get("defaultBlockState").getAsInt(),
                            block.get("explosionResistance").getAsDouble(),
                            block.get("friction").getAsDouble(),
                            block.get("speedFactor").getAsDouble(),
                            block.get("jumpFactor").getAsDouble(),
                            itemId
                    ).addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL).build()
            );

            JsonArray states = block.get("states").getAsJsonArray();

            ClassName blockStateSpecificClassName = ClassName.get(
                    "net.minestom.server.instance.block.states",
                    NameUtil.convertSnakeCaseToCamelCase(blockName.toLowerCase())
            );

            // Common blockStateSpecificClass structure
            TypeSpec.Builder blockStateSpecificClass = TypeSpec.classBuilder(blockStateSpecificClassName)
                    .addAnnotation(
                            AnnotationSpec.builder(Deprecated.class)
                                    .addMember("since", "$S", "forever")
                                    .addMember("forRemoval", "$L", false).build()
                    )
                    .addModifiers(Modifier.PUBLIC, Modifier.FINAL);
            // initStates method
            MethodSpec.Builder initStatesMethod = MethodSpec.methodBuilder("initStates")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC);

            int relativeId = 0;
            for (JsonElement s : states) {
                JsonObject state = s.getAsJsonObject();
                // Field
                FieldSpec stateField = FieldSpec.builder(
                        blockStateClassName,
                        blockName + "_" + relativeId
                ).initializer(
                        "new $T((short) $L, $T.$N)",
                        blockStateClassName,
                        state.get("id").getAsShort(),
                        blockClassName,
                        blockName
                ).addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL).build();
                // Add Field to class
                blockStateSpecificClass.addField(stateField);
                // Add field to initStates method
                initStatesMethod.addStatement(
                        "Block.$N.addBlockState($N)", blockName, stateField.name);
                relativeId += 1;
            }
            // Add initStates Method
            blockStateSpecificClass.addMethod(initStatesMethod.build());

            // Add initStates method refence to static block
            staticBlock.addStatement("$T.initStates()", blockStateSpecificClassName);

            // Write BlockState
            try {
                JavaFile.builder("net.minestom.server.instance.block.states", blockStateSpecificClass.build()).build().writeTo(outputFolder);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        blockClass.addStaticBlock(staticBlock.build());
        // Add ignore deprecations annotation
        blockClass.addAnnotation(AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "deprecation").build());

        // Write classes
        try {
            JavaFile.builder("net.minestom.server.instance.block", blockClass.build()).build().writeTo(outputFolder);
            JavaFile.builder("net.minestom.server.instance.block", blockStateClass.build()).build().writeTo(outputFolder);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void generateEntities(File inputFile, File outputFolder) {

    }

    private static void generateBlockEntities(File inputFile, File outputFolder) {

    }

    private static void generateItems(File inputFile, File outputFolder) {
        JsonArray items;

        try {
            items = GSON.fromJson(new JsonReader(new FileReader(inputFile)), JsonArray.class);
        } catch (FileNotFoundException e) {
            LOGGER.error("Failed to find items.json, stopped generating code for blocks", e);
            return;
        }
        ClassName materialClassName = ClassName.get("net.minestom.server.item", "Material");
        // Material
        TypeSpec.Builder materialClass = TypeSpec.classBuilder(materialClassName).addModifiers(Modifier.PUBLIC);
        materialClass.addField(FieldSpec.builder(String.class, "id").addModifiers(Modifier.PRIVATE, Modifier.FINAL).addAnnotation(NotNull.class).build());
        materialClass.addField(FieldSpec.builder(TypeName.BYTE, "maxStackSize").addModifiers(Modifier.PRIVATE, Modifier.FINAL).build());
        // Material constructor
        materialClass.addMethod(
                MethodSpec.constructorBuilder()
                        .addParameter(ParameterSpec.builder(String.class, "id").addAnnotation(NotNull.class).build())

                        .addStatement("this.id = id")
                        .addModifiers(Modifier.PUBLIC)
                        .build()
        );
        for(JsonElement i : items) {
            JsonObject item = i.getAsJsonObject();
            String itemName = item.get("name").getAsString();

            materialClass.addField(
                    FieldSpec.builder(
                            materialClassName,
                            itemName
                    ).initializer(
                            "new $T($S, $L, (byte) $L, $L, $L)",
                            materialClassName,
                            item.get("id").getAsString(),
                            item.get("depletes").getAsBoolean(),
                            item.get("maxStackSize").getAsByte(),
                            item.get("edible").getAsBoolean(),
                            item.get("fireResistant").getAsBoolean()
                    ).addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL).build()
            );

            // Write classes
            try {
                JavaFile.builder("net.minestom.server.item", materialClass.build()).build().writeTo(outputFolder);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
