group = "com.minestom.autogenerated"
apply(plugin = "java")

repositories {
    mavenCentral()
}
dependencies {
    val compileOnly by configurations

    // Jetbrains annotations
    compileOnly("org.jetbrains:annotations:20.1.0")
}

configure<JavaPluginConvention> {
    sourceSets {
        val version: String = (project.properties["mcversion"] ?: "1.16.5") as String
        getByName("main") {
            java {
                setSrcDirs(arrayListOf(version))
            }
        }
        getByName("test") {
            java {
                setSrcDirs(emptyList<Any?>())
            }
            resources {
                setSrcDirs(emptyList<Any?>())
            }
        }
    }
}
tasks {
    getByName<Test>("test") {
        enabled = false
    }
}